### ISSUE TITLE
文档有2个静态文件被墙

### ISSUE THREAD

**Issue by ClarkeCheng** [XTLS/XTLS.github.io#1]
[https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css](https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css)
[https://code.jquery.com/jquery-3.5.1.min.js](https://code.jquery.com/jquery-3.5.1.min.js)

如果可以，请替换成中国能访问的

![image](https://user-images.githubusercontent.com/17330505/103442717-c7261f80-4c93-11eb-919c-675d1982e880.png)

**Comment by badO1a5A90** [comment]
感谢反馈，已修复
https://github.com/XTLS/XTLS.github.io/pull/4
