### ISSUE TITLE
側邊目錄缺少到 streamSettings 頁面的導航

### ISSUE THREAD

**Issue by phlinhng** [XTLS/XTLS.github.io#13]
從側邊欄無法直接點擊到 [配置文件 - 傳輸方式 - StreamSettings](https://xtls.github.io/config/transport/#streamsettingsobject) 的頁面， `streamSettings` 作為配置 XTLS 的重要部份，應該在目錄中單獨列出。

**Comment by badO1a5A90** [comment]
菜单层级有待调整加强

**Comment by badO1a5A90** [comment]
菜单层级进行了一次调整. 加入了配置文件所有模块的展开, 但如果到StreamSettings还需要一次展开,似乎会使得菜单层级过多.
