### ISSUE TITLE
文档手机端排版问题

### ISSUE THREAD

**Issue by BioniCosmos** [XTLS/XTLS.github.io#3]
如题，DocPort 在手机端存在严重的排版问题。如显示不全，排版混乱等。

**Comment by BioniCosmos** [comment]
补图：（通过 Chrome 调试工具获取）
![xtls github io_(iPhone X)](https://user-images.githubusercontent.com/41363844/103450413-f1f29100-4cf0-11eb-907f-0fc7155a4fc8.png)

**Comment by badO1a5A90** [comment]
确实现在对移动端适配不佳，有待改进，感谢反馈。

**Comment by badO1a5A90** [comment]
感觉主要是column的移动适配有问题

**Comment by badO1a5A90** [comment]
https://github.com/XTLS/XTLS.github.io/commit/761201a1a41ea3ac74ed87c614a0bfa5d752ee69

**Comment by badO1a5A90** [comment]
以上commit已经修复问题

**Comment by BioniCosmos** [comment]
还没完全解决。顶栏显示不全，文章上面的分节目录会阻挡正文内容。

**Comment by badO1a5A90** [comment]
> 还没完全解决。顶栏显示不全，文章上面的分节目录会阻挡正文内容。

那个好像他故意设计了一个浮动所以遮挡了....可能干脆去掉比较好
