### ISSUE TITLE
acme.sh可以提供泛域名证书，推荐白话文第六章稍事修改

### ISSUE THREAD

**Issue by shenlijun** [XTLS/XTLS.github.io#41]

**Comment by badO1a5A90** [comment]
@ricuhkaen

**Comment by ricuhkaen** [comment]
感谢建议。

暂时的想法是，小小白白话文仅提供最简单、最基础的配置方式，手把手把一套流程跑通即可。

之后的优化、详解、进阶等，可以在 level 1 或者其他地方体现。

域名与证书相关，其实内容比较多，比如 biubiu 目前正在研究 IP 证书的内容、比如oscpStalping的优化等等，未来可能单独开坑
