### ISSUE TITLE
进阶文档 - 透明代理（TProxy）配置教程 里面有两处问题，望解答。

### ISSUE THREAD

**Issue by Acytoo** [XTLS/XTLS.github.io#80]
执行这篇教程中的 nftables 部分时，遇到了一些问题。

![screen](https://user-images.githubusercontent.com/18031762/111804422-08c97c80-890b-11eb-8ecb-e6d9bdc329d6.png)

机器是树莓派 4B，系统是最新 raspberry pi os（hostname 叫 redhat）,nftables版本以及报错信息如上图。

-----------------------------

另外，ip这个程序，在不同系统中的位置不同，但是没有歧义。建议把 ```nftables.service```里面的 ```/usr/sbin/ip```简化为 ```ip```

![s2](https://user-images.githubusercontent.com/18031762/111805276-d409f500-890b-11eb-8e19-630abffd110a.png)

**Comment by BioniCosmos** [comment]
感謝反饋。系統不同，很多東西都會有區別。

你可以試試把 priority 後面的 mangle 改為 -150。

service 文件中的 ip 必須是二進制文件的準確路徑，而不能只寫 ip，不過的確沒考慮到不同系統的路徑不同。
